### PR TITLE
Configuration, github pages, formatting

### PR DESCRIPTION
**Pull request by AKuHAK**
## Pull Request checklist

Note: these are not necessarily requirements

- [x] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

### CODE REVIEW

**Comment by AKuHAK** [comment]
Site backup now is online: you can see example of it here:
https://akuhak.github.io/SMS

**Comment by KrahJohlito** [comment]
Nice work, any chance of clang formatting the source files as well? I find the formatting is not as easy to read as other projects.. personal opinion

**Comment by AKuHAK** [comment]
> Nice work, any chance of clang formatting the source files as well? I find the formatting is not as easy to read as other projects.. personal opinion

I added clang - but the code is already formatted, As for me it looks pretty good, could you point out what exactly is bad to your opinion.

**Comment by KrahJohlito** [comment]
It’s hard to read, it’s not as easy to see where conditions end without looking for the /* comments *\ as other projects.. how ever it is still readable and as I said it’s a personal opinion, if you don’t want to change it that’s fine.

**Comment by AKuHAK** [comment]
> if you don’t want to change it that’s fine.

It is not about what I "dont want", I really don't see the need to perform such a manipulation. The code is formatted very well and follows its formatting throughout all the code. Clang-format will break most of @ EEUG formatting. As I understand you didn't like spaces everywhere - yeah in fact it is a bit annoying (or maybe you mean something different, isnt that brackets everywhere?). Clang format isn't that advanced, it has its limitations and in this particular code, it will break more than fix.

**Comment by KrahJohlito** [comment]
> > if you don’t want to change it that’s fine.
> 
> It is not about what I "dont want", I really don't see the need to perform such a manipulation. The code is formatted very well and follows its formatting throughout all the code. Clang-format will break most of @ EEUG formatting. As I understand you didn't like spaces everywhere - yeah in fact it is a bit annoying (or maybe you mean something different, isnt that brackets everywhere?). Clang format isn't that advanced, it has its limitations and in this particular code, it will break more than fix.

I didn’t say it was bad nor did I claim it was inconsistent, I said I don’t find it as easy to read as other projects.

Yes not only the spaces everywhere but also the indentation is only one space which makes it more difficult to read than a tab or four spaces.. again though this is only my opinion and doesn’t make it unreadable or “bad”.

**Comment by AKuHAK** [comment]
I will take a look into clang - maybe it is possible to retain most of the current formatting and just fix things that are difficult for code reading. Yes, one space indentation looks bad, and also there are many empty spaces. I will take a look at it later.

**Pull request merged**
